### ISSUE TITLE
Migrate to Google Analytics 4 (GA4)

### ISSUE THREAD

**Issue by chalin** [vitessio/website#1098]
This as part of a CNCF-wide effort to upgrade project websites to GA4. For context, see:

- https://github.com/cncf/techdocs/issues/108

Current GA info (before work started on this issue):

- Analytics library currently being used is `analytics.js`
- Using Hugo 0.96.0 and its internal GA template, so activating GA4 can achieved via a config setting update.

### Tasks (stages 1 & 2)

- [x] Create a GA4 site tag using the GA4 setup assistant from the UA site tag
  - The new measurement ID is **`G-JWT03RNV4P`**.
- [x] Manually [connect] UA tag to GA4 tag from GA4 data stream.
- [x] Switch to using GA4 tag and confirm that both tags are still receiving events:
  - [x] #1102
  - [x] Confirm that the GA4 site tag is receiving events -- for screenshot, see below
  - [x] Confirm that the UA site tag, `UA-163836834-1`, is still receiving events -- for screenshot, see below

Related:

- An earlier PR over this repo that involved analytics: https://github.com/vitessio/website/pull/435
- Benchmarking site issue: https://github.com/vitessio/arewefastyet/issues/297

/cc @nate-double-u 

[connect]: https://support.google.com/analytics/answer/9973999

**Comment by chalin** [comment]
About 10 minutes have passed since this was deployed to the production server and the UA property is still receiving events:

> <img width="1518" alt="image" src="https://user-images.githubusercontent.com/4140793/184181188-c15f3c67-8393-4bad-b0de-c442fe5b49e8.png">

Notice the data in the histogram after the -11min mark.

The GA4 site tag is receiving events too now:

> <img width="553" alt="image" src="https://user-images.githubusercontent.com/4140793/184181737-0e226670-bda3-4f2c-ab83-0ae0465ca52b.png">

**Comment by chalin** [comment]
All done!

**Comment by chalin** [comment]
Benchmarking site issue:

- https://github.com/vitessio/arewefastyet/issues/297
