### ISSUE TITLE
Broken links umbrella issue

### ISSUE THREAD

**Issue by nate-double-u** [vitessio/website#1169]
The site has broken links throughout.

This umbrella issue tracks issues for broken internal links, by version (to help set priority)

### Internal links issues

- [x] #1170🔝
- [x] https://github.com/vitessio/website/issues/1171 🔝
- [x] https://github.com/vitessio/website/issues/1172 
- [x] https://github.com/vitessio/website/issues/1173
- [x] https://github.com/vitessio/website/issues/1174
- [ ] https://github.com/vitessio/website/issues/1175 (archives and other un-versioned docs)

### Tools

To get the results the issues are based on, run:
```
make link-checker-setup
make check-internal-links
```
EDIT Jan 25, 2023: v16 is now the top priority

**Comment by deepthi** [comment]
The highest priority would be v15, then v14, then the rest.

**Comment by PaarthAgarwal** [comment]
I had a look on all of these. Do we replace those links or delete them?

**Comment by nate-double-u** [comment]
I'd prefer replacement if possible. The links should all be internal, so there should be pages that they can point to.

**Comment by deepthi** [comment]
@nate-double-u should we close the issues for v14 etc. since they are now archived?
Instead it may be worth running broken links checks on current docs - v19, v18 and v17. v16 is already fixed.

**Comment by nate-double-u** [comment]
I've closed the older ones, and agree we should check that the newer versions are getting checked. Closing this as complete.
