### ISSUE TITLE
LFX 2024 Term 3: Add new getting started examples

### ISSUE THREAD

**Issue by frouioui** [vitessio/website#1798]
## Description

For this third term of the 2024 LFX mentorship program, we would like to add more getting started guides and code examples to help new users of Vitess to get up to speed with the project. With the project being complex as it is, its lack of examples makes it harder for people to adopt. We would then like to add a new guide on at least the following topics:

- Backups
- VReplication
- FKs
- Managed
- Improve the troubleshooting / common issues guide

More categories can be added as we realize we need some guides in some areas. The goal of the internship is to quickly grow the mentee's understanding of Vitess have them contribute real code examples (through shell scripts most likely) to help other users.

## Milestones

Below is a list of milestones to reach throughout the whole internship. These milestones will help to provide some structure to the internship and help sets some goals.

- [x] First week
  - [x] Merge at least two PRs, both related to the examples. One on the website repository, another one in the vitess repository.
  - [x] These two PRs can be related to minor improvements to the examples.
    - [x] https://github.com/vitessio/website/pull/1848
    - [x] https://github.com/vitessio/website/pull/1847 
  - [ ] You should have a fully functional development environment on both repositories.
  - [x] Expand on the troubleshooting guide, based on your exploration of the getting started guide, report any problem to the troubleshooting page and detail how you went around these problems.
  - [x] When running the getting started guide run both the K8S and Local examples.
  - [x] When running the getting started guide, make sure VTAdmin is running. Explore what VTAdmin is, and try to see how you can incorporate it a bit more to the getting started guide docs. Right now VTAdmin is barely mentioned in the getting started guide.
  - [x] Start the exploration of Vitess, the goal is to go through most of the Vitess features and understand what's missing in the getting started guide and become more familiar with Vitess. Gaps in the docs should be found.
- [x] Second week
	- [x] Continue that exploration.
	- [ ] Come up with a list of things of guides that are missing based on the features you explored last and this week.
	  - [ ] https://github.com/vitessio/website/pull/1856 
	- [ ] Make at least two major additions to the examples that cover additional concepts. Preferably adding new steps after the 30x examples. By the end of the 30x examples, we have a very typical vitess cluster that can cover most of the use cases, we want to build on top of that cluster by adding new guides, e.g. 40x, 50x, 60x, etc. For instance: continue the 40x step to add how to take and restore backups in the local examples, the K8S part already has some content on this. Things like: backups, schema changes, mysql configuration, etc can be covered.
	  - [ ] https://github.com/vitessio/vitess/pull/16893 
	  - [ ] https://github.com/vitessio/website/pull/1861
- [ ] Third week and beyond
  - [ ] Incorporate the list of things we came up with during the second week.
  - [ ] 2 major additions / PRs should be contributed each week on average. These additions should be meaningful and long-lasting, the PRs will be reviewed by several maintainers to ensure they fit these criterias. 
  - [ ] Changes to the troubleshooting guide should be done as soon as a problem is encountered.
- [ ] Last week
  - [ ] Write a blog post about everything you have done and contributed. This blog post will highlight your work and will be shared with the rest of the community.
  - [ ] Participate in November's monthly meeting, where all contributors and users meet and discuss about vitess. In this monthly meeting, you'll be able to share what you worked on and get feedback from the community.

**Comment by AayushSaini101** [comment]
@frouioui I am interested in this project. I have contributed in asyncapi cli and writing technical writing as well. I have contributed in this documentation: https://www.asyncapi.com/docs/tools/cli/usage and I explored many architecture regarding vitess: https://www.youtube.com/watch?v=q65TleTn2vg&t=1200s and found very interesting. If there are any prerequisite for this project, please let me know, i am happy to contribute thanks :)

**Comment by Ayush9026** [comment]
@frouioui sir i am also interested in this project i am also contributing to other CNCF projects.

**Comment by that-avg-dev** [comment]
@frouioui hii , I am kairvee and would like to take up this issue under LFX phase 3 , as it perfectlty aligns with my interest and skills

**Comment by rahulbansal3005** [comment]
Hi @frouioui. I am rahul and i am very interested to work on this issue, in upcoming Term in LFX. I went through the Repo also to get an understanding, if there is any pre-requisite please let me know.

**Comment by arunavabasucom** [comment]
@frouioui  would like to work on this project .

**Comment by mhmohona** [comment]
Hello @frouioui,I've been reviewing the topics mentioned in the issue discription. I've found some existing documentation, but I'm missing links for a few topics. Could you please clarify the following:

1. I've located these existing documents:
   - [Backups](https://vitess.io/docs/21.0/reference/backup-and-restore/)
   - [VReplication](https://vitess.io/docs/21.0/reference/vreplication/)
   - [Foreign Keys (FKs)](https://vitess.io/docs/21.0/user-guides/vschema-guide/foreign-keys/)
   - [Troubleshooting / Common Issues Guide](https://vitess.io/docs/19.0/user-guides/configuration-basic/troubleshooting/)

2. However, I couldn't find existing documentation for:
   - Managed 

3. For clarity on the project scope:
   - For topics with existing documentation (Backups, VReplication, FKs, Troubleshooting), should the mentee rewrite or improve these guides?
   - For topic without existing documentation (Managed Vitess), should the mentee create new "Getting Started" guides from scratch?
   - Is it correct that all new or rewritten guides should include code examples, preferably as shell scripts?

This approach would ensure that we have comprehensive "Getting Started" guides with practical code examples for all specified topics. Could you confirm if this understanding is correct?

**Comment by Shrutim1505** [comment]
@frouioui would love to contribute in this project .

**Comment by eeshaanSA** [comment]
Great research, @mhmohona. As a fellow contributor, I'm also interested in this project and have similar questions. Looking forward for your thoughts and clarifications. @frouioui

**Comment by frouioui** [comment]
This LFX mentorship is terminated, closing this issue for now.
